#!/usr/bin/env python3
"""Generate a devcontainer.json from base.jsonc plus whatever this machine adds to it.

    python3 build.py --target odoo-dev            # writes into WORKTREE_ROOT/.devcontainer
    python3 build.py --target odoo-dev --check     # says what would change, writes nothing
    python3 build.py --target <name> --base <repo>/devcontainer.base.jsonc \
                     --out <repo>/.devcontainer/devcontainer.json

A repo cloned beside this one contributes a devcontainer.fragment.json naming the mounts, runArgs
and env it needs, per target. Nothing cloned means nothing merged: the container is then the plain
base, and it still builds and runs. That is the point of generating the file rather than committing
one.

Arrays append in repo-name order. A containerEnv key ending in `+` appends to the comma-separated
value already there, so two fragments can add to one variable. @KEY@ placeholders come from
config.py.
"""

import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import config  # noqa: E402

HEADER = """// Generated by devcontainer/build.py for target {target}. Do not edit.
// From {base}
// Fragments: {fragments}
"""


def strip_comments(text):
    """Drop // and /* */ outside strings, so json can read a JSONC file."""
    out, index, in_string, escaped = [], 0, False, False
    while index < len(text):
        char = text[index]
        if in_string:
            out.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
            continue
        if char == '"':
            in_string = True
            out.append(char)
            index += 1
            continue
        if text.startswith("//", index):
            end = text.find("\n", index)
            index = len(text) if end < 0 else end
            continue
        if text.startswith("/*", index):
            end = text.find("*/", index)
            index = len(text) if end < 0 else end + 2
            continue
        out.append(char)
        index += 1
    return "".join(out)


def drop_trailing_commas(text):
    """A devcontainer.json may carry them and VS Code accepts them; json.loads does not."""
    out, index, in_string, escaped = [], 0, False, False
    while index < len(text):
        char = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
        elif char == '"':
            in_string = True
        elif char == ",":
            rest = text[index + 1:].lstrip()
            if rest[:1] in ("}", "]"):
                index += 1
                continue
        out.append(char)
        index += 1
    return "".join(out)


def read_jsonc(path):
    try:
        return json.loads(drop_trailing_commas(strip_comments(path.read_text())))
    except json.JSONDecodeError as error:
        sys.exit(f"{path}: {error}")


def fragments(repo_root, target):
    """Every fragment for this target, in repo-name order so the merge is reproducible."""
    found = []
    for path in sorted(pathlib.Path(repo_root).glob("*/devcontainer.fragment.json")):
        fragment = read_jsonc(path)
        piece = fragment.get("targets", {}).get(target)
        if piece:
            found.append((fragment.get("name") or fragment.get("gateway") or path.parent.name, piece))
    return found


def merge(into, piece, source):
    for key, value in piece.items():
        if isinstance(value, list):
            into.setdefault(key, []).extend(value)
        elif isinstance(value, dict):
            target = into.setdefault(key, {})
            for name, item in value.items():
                if name.endswith("+"):
                    name = name[:-1]
                    current = target.get(name)
                    target[name] = f"{current},{item}" if current else item
                else:
                    if name in target and target[name] != item:
                        print(f"  {source} overrides {key}.{name}")
                    target[name] = item
        else:
            if key in into and into[key] != value:
                print(f"  {source} overrides {key}")
            into[key] = value


def expand(node, values):
    if isinstance(node, str):
        return re.sub(r"@([A-Z_]+)@", lambda hit: values[hit.group(1)], node)
    if isinstance(node, list):
        return [expand(item, values) for item in node]
    if isinstance(node, dict):
        return {key: expand(item, values) for key, item in node.items()}
    return node


def main():
    values = config.load()
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--base", type=pathlib.Path)
    parser.add_argument("--out", type=pathlib.Path)
    parser.add_argument("--repo-root", default=values["REPO_ROOT"])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    base_path = args.base or pathlib.Path(__file__).resolve().parent / "base.jsonc"
    out_path = args.out or pathlib.Path(values["WORKTREE_ROOT"]) / ".devcontainer/devcontainer.json"
    result = read_jsonc(base_path)
    used = []
    for name, piece in fragments(args.repo_root, args.target):
        used.append(name)
        merge(result, piece, name)

    try:
        result = expand(result, values)
    except KeyError as error:
        sys.exit(f"no config key for placeholder @{error.args[0]}@")
    text = HEADER.format(
        target=args.target,
        base=base_path,
        fragments=", ".join(used) or "none cloned",
    ) + json.dumps(result, indent=2) + "\n"

    if args.check:
        current = out_path.read_text() if out_path.exists() else ""
        print(f"{out_path}: {'unchanged' if current == text else 'would change'}")
        print(f"fragments: {', '.join(used) or 'none cloned'}")
        return 0
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # A generated file replaces whatever is there, and writing through a symlink would edit its
    # target instead.
    if out_path.is_symlink():
        out_path.unlink()
    out_path.write_text(text)
    print(f"wrote {out_path} ({', '.join(used) or 'base only, nothing to merge'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
